[build]
  publish = "_site"
  command = "npx eleventy"

# Default
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/*"
  to = "/fr/:splat"
  status = 302
  conditions = {Language = ["fr"]}
